FROM registry.fedoraproject.org/fedora:44

RUN dnf install -y \
        desktop-file-utils \
        git \
        gtk3 \
        gtksourceview4 \
        python3 \
        python3-cairo \
        python3-gobject \
        rpm-build
